# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs every 6 hours.
on:
  schedule:
    # every 6 hours
    - cron: "0 */6 * * *"

  # This command allows us to run the Action automatically from the Actions tab.
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks repo under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3

    # Generates the snake  
    - uses: Platane/snk@master
      id: snake-gif
      with:
        github_user_name: Baha-Bouazizi
        # these next 2 lines generate the files on a branch called "output". This keeps the main branch from cluttering up.
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    # Debug the git status and configuration
    - name: Debug Git Status
      run: |
        git status
        git remote -v
        git branch -a

    # Push the changes
    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        publish_branch: main

    - uses: crazy-max/ghaction-github-pages@v2
      with:
        # the output branch we mentioned above
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
